# Generated by Django 3.1 on 2021-08-12 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210812_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nike_name',
            new_name='nikename',
        ),
    ]
