# Generated by Django 3.1 on 2021-08-19 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210813_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='password',
            field=models.TextField(default='pbkdf2:sha256:150000$VbTaukm0$b67d55005ae5302bcdf4bd3752e46de3b935ec3c2054a49122bb577789152a7a'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='token',
            field=models.TextField(default='pbkdf2:sha256:150000$Lu8HopmS$be3b212f450c66b59a0a4199236e3e325998fb902b58e8bb38d9ab90f27b745f'),
        ),
    ]
