# Generated by Django 3.1 on 2021-08-19 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210820_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='password',
            field=models.TextField(default='pbkdf2:sha256:150000$sxRshi9X$0c19126fe0894a211e6aa014c1baa0a45b1d8e369cc0b2c429d5cf91d1bc375f'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='token',
            field=models.TextField(default='pbkdf2:sha256:150000$zTR8M4XN$00a72531ff6208f6044ca14b020f2948831d3e811be1357cdfeb3f059f41298b'),
        ),
    ]
