# Generated by Django 3.1 on 2021-08-19 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210820_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='password',
            field=models.TextField(default='pbkdf2:sha256:150000$m46DqNDs$b91656ba9e04ff869b79da95e5dad05cf9151d2f2f7842aa392a985415652ea5'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='token',
            field=models.TextField(default='pbkdf2:sha256:150000$KJO7jsyo$e845895ffe0aa14ccec709e685b5bec61293ab792c4fd79fa6f3130fafc4ed51'),
        ),
    ]
