# Generated by Django 3.1 on 2021-08-20 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20210820_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='password',
            field=models.TextField(default='pbkdf2:sha256:150000$OQm6Gk0p$53083dba69efacc81d94074f586d3fcf578781581b39f2477e62d45285e6ac5f'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='token',
            field=models.TextField(default='pbkdf2:sha256:150000$DfcjddZz$674b35f02a9ca7d75f65c423b0b5b5aef5a0b8caffd728219fd91618d1af54ee'),
        ),
    ]
