# Generated by Django 3.1 on 2021-08-20 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20210820_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='password',
            field=models.TextField(default='pbkdf2:sha256:150000$Z6xPMST3$c4cd1ff1d7638684fbda4c66d9074d80a27750357f9b4bd2fee72b57a3b1604a'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='token',
            field=models.TextField(default='pbkdf2:sha256:150000$QWyOhhK4$33895daf6013e3cbea0602374833b10ae0c6ff682e74ff89f88ae6f3814d14ca'),
        ),
    ]
