# Generated by Django 3.1 on 2021-08-20 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20210820_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='password',
            field=models.TextField(default='pbkdf2:sha256:150000$K0oI8l3P$cb4db8f4ad11a3b3e1b41db24f582f6858e827cba9feaadc10fbb0085f16f823'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='token',
            field=models.TextField(default='pbkdf2:sha256:150000$JoIixsTy$c86dd712556950d7943b9cb00eb3c3289eab20442fe0d633726060ec00b5f1b1'),
        ),
    ]
