# Generated by Django 3.1 on 2021-08-20 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20210820_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='password',
            field=models.TextField(default='pbkdf2:sha256:150000$uTchqLup$29f04766a11a9dfdefde3bbb10221459624014efb1e26e7f6970ad8d81977392'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='token',
            field=models.TextField(default='pbkdf2:sha256:150000$pzJSnBBG$5612157c1c05f44c708ad8fade90602ea6e63053dd43415356966ad93e78e365'),
        ),
    ]
