# Generated by Django 3.1 on 2021-08-20 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20210820_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='password',
            field=models.TextField(default='pbkdf2:sha256:150000$0J2JxOZL$d6ba068c029311f4db9e98e3470289962da301de8553a30e3e31772b6c9648d5'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='token',
            field=models.TextField(default='pbkdf2:sha256:150000$EaEfTFaq$077d0944cf65de09a4bb99cd20f199ed5586059dc6db7d5e0f73d36c1a2986f0'),
        ),
    ]
