# Generated by Django 3.1 on 2021-08-20 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20210820_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='password',
            field=models.TextField(default='pbkdf2:sha256:150000$3w8z8ac8$c02242e3d0d52fbd19c3ccf05dfd3d1359635daa9d5df50e79be3b618dae8ef4'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='token',
            field=models.TextField(default='pbkdf2:sha256:150000$vTnTwkRN$8a36adfe0f9badee07ddfcd8a62b87b8afab18f7f886e20d7930b41737f16819'),
        ),
    ]
