# Generated by Django 3.1 on 2021-08-20 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20210820_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='password',
            field=models.TextField(default='pbkdf2:sha256:150000$q8c9YyZe$5bc1d1efbb47b78c449fd722882fd6d86ab5188cf100cd1d4c0f74c9b3440795'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='token',
            field=models.TextField(default='pbkdf2:sha256:150000$GYxBf95f$4a838c88c2b62347de4eb93760db26be85e26ac20071fa3bffa88710fd43a718'),
        ),
    ]
