# Generated by Django 3.1 on 2021-08-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20210820_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='password',
            field=models.TextField(default='pbkdf2:sha256:150000$lEU1r3Qm$12a9070166efee4ec40c50c3f28c678a17d49e2cbfa98f2188f9fe8826a02dd5'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='token',
            field=models.TextField(default='pbkdf2:sha256:150000$ENMVeHil$6b1cbd36db47314a24ca41e3c09b8a8bd90d9dc8e40fe80c153f0fca88b32274'),
        ),
    ]
