# Generated by Django 3.1 on 2021-08-20 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20210820_0746'),
        ('routes_access', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('nameAccess', models.TextField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LinksMenus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes_access.links')),
            ],
        ),
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MenusRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes_access.menus')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes_access.role')),
            ],
        ),
        migrations.DeleteModel(
            name='ModulesAccess',
        ),
        migrations.DeleteModel(
            name='RoutesLinks',
        ),
        migrations.AlterField(
            model_name='userrole',
            name='id_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes_access.role'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AddField(
            model_name='linksmenus',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes_access.menus'),
        ),
    ]
