# Generated by Django 3.1 on 2021-08-20 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes_access', '0002_auto_20210820_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='menusrole',
            name='edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menusrole',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
