# Generated by Django 3.1 on 2021-08-22 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes_access', '0003_auto_20210820_0805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrole',
            old_name='id_role',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='userrole',
            old_name='id_user',
            new_name='user',
        ),
    ]
